# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todo2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for todo2
  target 'todo2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'todo2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for todo2-tvOS

  target 'todo2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
